language: bash
services: docker
sudo: required

env:
  - IMAGE=dockerfile/php-dev/5.6/
  - IMAGE=dockerfile/php-dev/7.0/
  - IMAGE=dockerfile/php-dev/7.1/
  - IMAGE=dockerfile/php-dev/latest/

before_script:
  - cd $IMAGE

script:
  - docker build .

after_script:
  - docker images
